### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by yesnet0** [disclose/diosts#1]
Conditions: 
Running the script using the following list of domains on Ubuntu 18.04 LTS (go version go1.10.4 linux/amd64)
```
facebook.com
google.com
youtube.com
twitter.com
instagram.com
linkedin.com
microsoft.com
apple.com
wikipedia.org
plus.google.com
```

Result:
```
panic: runtime error: index out of range

goroutine 7 [running]:
github.com/disclose/diosts/internal/pkg/discloseio.FromSecurityTxt(0xc4201a8700, 0x7e9d16)
	/root/go/src/github.com/disclose/diosts/internal/pkg/discloseio/discloseio.go:71 +0x3a1
github.com/disclose/diosts/internal/app/run.(*Writer).Start.func1(0xc42010e300)
	/root/go/src/github.com/disclose/diosts/internal/app/run/writer.go:50 +0x195
created by github.com/disclose/diosts/internal/app/run.(*Writer).Start
	/root/go/src/github.com/disclose/diosts/internal/app/run/writer.go:34 +0x5c
```

Expected:
Normal completion.

**Comment by gi-el** [comment]
Panic was due to silly wrong logic. However, I want to fix two more things:
1. Be more strict about rejecting security.txt. Seems that we get redirected to generic pages sometimes, try to parse the HTML, and end up with 1000s of error messages. So, if we encounter a field that is not `field: value`, I'll bail out and declare no security.txt found
2. Do some validation for mandatory fields; if we miss a mandatory field, reject security.txt instead of creating an invalid output.
